apiVersion: v1
kind: Secret
metadata:
  name: opsmx-agent-controller-auth
type: Opaque
data:
  authtoken: {{ (lookup "v1" "Secret" .Release.Namespace "opsmx-agent-controller-auth") | default (randAlphaNum 20 | b64enc) }}

# {{- $existingSecret := (lookup "v1" "Secret" .Release.Namespace "opsmx-agent-controller-auth") -}}
# {{- if not $existingSecret }}
# apiVersion: v1
# kind: Secret
# metadata:
#   name: opsmx-agent-controller-auth
# type: Opaque
# data:
#   authtoken: {{ randAlphaNum 20 | b64enc | quote }}
# {{- else }}
# apiVersion: v1
# kind: Secret
# metadata:
#   name: opsmx-agent-controller-auth
# type: Opaque
# data:
#   authtoken: {{ $existingSecret.data.authtoken }}
# {{- end }}  
